version: "3.8"

networks:
  blog_net:

volumes:
  data:
  init:

services:

  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - /var/lib/docker/volumes/html:/usr/share/nginx/html

  nacos:
    image: nacos/nacos-server:2.2.1
    ports:
      - "8848:8848"
    environment:
      - "MODE=standalone"
    restart: always
    networks:
      - blog_net

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - /var/lib/docker/volumes/mysql/data:/var/lib/mysql # 映射数据，防止容器重启丢失数据
      - /var/lib/docker/volumes/mysql/data:/etc/mysql/conf.d/
      - /var/lib/docker/volumes/mysql/init:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - blog_net